// Service worker for /book/ only (generated by book-drafts/build.py).
// Network first (content stays fresh), cache as offline fallback. The whole book is precached.
const CACHE = 'proof-book-92a6c45b';
const CORE = [
  '/book/book.css?v=7cb329d7',
  '/book/book.js?v=7cb329d7',
  '/style.css',
  '/fonts/fonts.css',
  '/fonts/righteous-latin.woff2',
  '/fonts/righteous-latin-ext.woff2',
  '/fonts/jetbrainsmono-latin.woff2',
  '/fonts/jetbrainsmono-latin-ext.woff2',
  '/favicon.svg',
  '/bringin-logo.svg',
  '/book/',
  '/book/en/',
  '/book/en/ai/',
  '/book/en/autonomy/',
  '/book/en/big-tech/',
  '/book/en/bitcoin-privacy/',
  '/book/en/browser/',
  '/book/en/checklist/',
  '/book/en/email/',
  '/book/en/first-wallet/',
  '/book/en/glossary/',
  '/book/en/hardware-wallet/',
  '/book/en/introduction/',
  '/book/en/keys/',
  '/book/en/lightning-and-euros/',
  '/book/en/messages/',
  '/book/en/network/',
  '/book/en/node/',
  '/book/en/nostr/',
  '/book/en/passwords/',
  '/book/en/phone/',
  '/book/en/privacy/',
  '/book/en/savings/',
  '/book/en/seed/',
  '/book/en/self-hosting/',
  '/book/en/work/'
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }))
  );
});
